#--------directives definitions-----------
#root
#index
#return
#autoindex
#cgi
#upload
#error_pages
#max_body_size
#alias
#methods
#listen
#server_names
#locations
#-----------------------------------------



server {
    listen 127.0.0.1:8000;
    server_name localhost listen root;


    # location / {
    #     methods GET;
    #     root www/;
    # }

    error_page 404 /404.html;
    client_max_body_size 1000000;

    location / {
        index index.html;
        methods POST GET;
        upload_store /Users/eaboudi/Desktop/httpserver/UPLOADS; #need to fix this 
        root /Users/eaboudi/Desktop/httpserver;

    }
    root /Users/eaboudi/Desktop/httpserver;
    #   location /lol {
    #     cgi .php /usr/bin/php;
    #     index index.html;
    #     autoindex on;
    #     methods POST GET;
        # upload_store /home/sessarhi/Desktop/httpserver/; #need to fix this 
    #     root /home/sessarhi/Desktop/httpserver;

    # }
    location /CGI_SCRIPTS
    {
        methods GET POST;
        upload_store /Users/eaboudi/Desktop/httpserver/UPLOADS;
        cgi .php  /Users/eaboudi/Desktop/httpserver/CGI_SCRIPTS/php_cgimac;
        cgi .py /usr/bin/python3;
    }
    
}





# server {
#     listen 127.0.0.1:8000;
#     server_name localhost listen root;


#     # location / {
#     #     methods GET;
#     #     root www/;
#     # }

#     error_page 404 /404.html;
    #   client_max_body_size 1000000;

#     location / 
#     {
#         index index.html;
#         methods POST GET;
#         upload_store /Users/eaboudi/Desktop/httpserver/uploads; #need to fix this 
#         root /Users/eaboudi/Desktop/httpserver;

#     }
#     root /Users/eaboudi/Desktop/httpserver;
#     location /lol 
#     {
#         cgi .php /usr/bin/php;
#         index index.html;
#         autoindex on;
#         methods POST GET;
#         upload_store /Users/eaboudi/Desktop/httpserver/uploads; #need to fix this 
#         root /Users/eaboudi/Desktop/httpserver;

#     }

#     location /CGI_SCRIPTS
#     {
#         methods GET;
#         # alias /usr/bin/php;
#         cgi .php /usr/bin/php;
#     }
# }

# server {
#     listen 127.0.0.1:8081;
#     server_name api.local;

#     error_page 404 /api_404.html;
#     client_max_body_size 2000000;

#      location / {
#         index index.html;
#         methods POST GET;
#         upload_store /Users/eaboudi/Desktop/httpserver/uploads; #need to fix this 
#         root /Users/eaboudi/Desktop/httpserver;

#     }
  
# }



