server {
    listen 127.0.0.1:8000;
    server_name localhost listen root;

    error_page 404 /404.html;
    client_max_body_size 1000000;

    location / {
        methods POST GET;
        upload_store /home/sessarhi/Desktop/httpserver; #need to fix this 

        root /var/www/html;
    }
    
    
}

# server {
#     listen 10.12.7.2:8081;
#     server_name api.local;

#     error_page 404 /api_404.html;
#     client_max_body_size 2000000;
  
# }
